name: Spying

on:
  schedule:
    - cron: '5 21 * * *'

jobs:
  spy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build containers and run code
        run: docker-compose run --rm puppeteer yarn start
        env:
          ESPIONAGE_URLS: ${{ secrets.ESPIONAGE_URLS }}
          SES_FROM: ${{ secrets.SES_FROM }}
          SES_TO: ${{ secrets.SES_TO }}
          SES_SUBJECT: ${{ secrets.SES_SUBJECT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
